# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'EyuLibrary-ios_Example' do
    
  #国内纯穿山甲变现（含友盟，AF及广点通投放）
  #pod 'EyuLibrary-ios',:subspecs => ['Core','byte_dance_ads_sdk','um_sdk', 'af_sdk', 'gdt_action'], :path => '../'

  #国内聚合变现：穿山甲、广点通、mtg、（含友盟，AF及广点通投放）
#  pod 'EyuLibrary-ios',:subspecs => ['Core','byte_dance_ads_sdk','um_sdk', 'af_sdk', 'gdt_action','gdt_ads_sdk', 'mtg_ads_sdk'], :path => '../'
  
  #国内外聚合变现：FB、Admob、穿山甲、广点通、mtg、unity、vungle、iron source、Applovin（含友盟，AF及广点通投放，firebase）
  pod 'EyuLibrary-ios',:subspecs => ['Core','byte_dance_ads_sdk','um_sdk', 'af_sdk', 'gdt_action','gdt_ads_sdk', 'mtg_ads_sdk', 'fb_ads_sdk', 'unity_ads_sdk', 'vungle_ads_sdk', 'applovin_ads_sdk', 'iron_ads_sdk', 'firebase_sdk', 'crashlytics_sdk'], :path => '../'
  target 'EyuLibrary-ios_Tests' do
    inherit! :search_paths

    
  end
end
